CREATE INDEX `documents_1` ON `documents` (id_folder)
CREATE INDEX `documents_2` ON `documents` (status)
CREATE INDEX `document_comments_1` ON `document_comments` (id_document)
CREATE INDEX `document_sharing_1` ON `document_sharing` (id_user, id_document)
CREATE INDEX `document_filters_1` ON `document_filters` (id_author)
CREATE INDEX `document_reports_1` ON `document_reports` (id_user)
CREATE INDEX `user_bulk_rights_1` ON `user_bulk_rights` (id_user)
CREATE INDEX `user_action_rights_1` ON `user_action_rights` (id_user)
CREATE INDEX `user_metadata_rights_1` ON `user_metadata_rights` (id_user, id_metadata)
CREATE INDEX `ribbon_user_rights_1` ON `ribbon_user_rights` (id_ribbon, id_user)
CREATE INDEX `group_bulk_rights_1` ON `group_bulk_rights` (id_group)
CREATE INDEX `group_action_rights_1` ON `group_action_rights` (id_group)
CREATE INDEX `group_metadata_rights_1` ON `group_metadata_rights` (id_group, id_metadata)
CREATE INDEX `ribbon_group_rights_1` ON `ribbon_group_rights` (id_ribbon, id_group)
CREATE INDEX `metadata_values_1` ON `metadata_values` (id_metadata)
CREATE INDEX `folders_1` ON `folders` (id_parent_folder)
CREATE INDEX `processes_1` ON `processes` (id_document)
CREATE INDEX `processes_2` ON `processes` (id_author)
CREATE INDEX `processes_3` ON `processes` (workflow1, workflow2, workflow3, workflow4)
CREATE INDEX `process_comments_1` ON `process_comments` (id_process)
CREATE INDEX `notifications_1` ON `notifications` (id_user)
CREATE INDEX `password_reset_hashes_1` ON `password_reset_hashes` (id_user)
CREATE INDEX `ribbons_1` ON `ribbons` (id_parent_ribbon)
CREATE INDEX `file_storage_locations_1` ON `file_storage_locations` (type)
CREATE INDEX `file_storage_locations_2` ON `file_storage_locations` (name)
CREATE INDEX `services_1` ON `services` (system_name)
CREATE INDEX `users_1` ON `users` (last_login_hash)
CREATE INDEX `document_metadata_history_1` ON `document_metadata_history` (id_document)
CREATE INDEX `document_locks_1` ON `document_locks` (id_document, status)