CREATE TABLE IF NOT EXISTS `USERS` (
    `USER_ID` INT(32) PRIMARY KEY AUTO_INCREMENT,
    `USERNAME` VARCHAR(256) NOT NULL,
    `PASSWORD` VARCHAR(256) NULL,
    `FULLNAME` VARCHAR(256) NULL,
    `EMAIL` VARCHAR(256) NULL,
    `IS_ACTIVE` INT(1) NOT NULL DEFAULT 1,
    `EMAIL_ENABLED` INT(1) NOT NULL DEFAULT 1,
    `DATE_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
)